// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	hertz_demo "hertz-project/biz/router/hertz_demo"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hertz_demo.Register(r)

}
